<?php

return [
    /*
    |--------------------------------------------------------------------------
    | API Route Prefix
    |--------------------------------------------------------------------------
    |
    | This prefix will be used for all API routes generated by EvolveAPI.
    |
    */
    'route_prefix' => 'api',

    /*
    |--------------------------------------------------------------------------
    | Documentation Settings
    |--------------------------------------------------------------------------
    |
    | Configure the documentation generation and display settings.
    |
    */
    'docs' => [
        'enabled' => true,
        'route' => 'docs',
        'middleware' => ['web'],
        'title' => 'API Documentation',
    ],

    /*
    |--------------------------------------------------------------------------
    | Response Settings
    |--------------------------------------------------------------------------
    |
    | Configure how API responses are formatted.
    |
    */
    'responses' => [
        'include_meta' => true,
        'wrap_response' => true,
        'meta_key' => 'meta',
        'data_key' => 'data',
    ],
];
