<?php

return [
    /*
    |--------------------------------------------------------------------------
    | API Route Prefix
    |--------------------------------------------------------------------------
    |
    | This prefix will be used for all API routes generated by EvolveAPI.
    |
    */
    'route_prefix' => 'evolve-api',

    /*
    |--------------------------------------------------------------------------
    | API Configuration
    |--------------------------------------------------------------------------
    |
    | Configure the behavior of the Evolve API package.
    |
    */
    'logging' => [
        // Enable or disable route registration logging
        'routes' => env('EVOLVE_API_LOG_ROUTES', false),
        
        // Log level for route registration (debug, info, notice, warning, error, critical, alert, emergency)
        'level' => env('EVOLVE_API_LOG_LEVEL', 'debug'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Documentation Settings
    |--------------------------------------------------------------------------
    |
    | Configure the documentation generation and display settings.
    |
    */
    'docs' => [
        'enabled' => true,
        'route' => 'docs',
        'middleware' => ['web'],
        'title' => 'API Documentation',
    ],

    /*
    |--------------------------------------------------------------------------
    | Response Settings
    |--------------------------------------------------------------------------
    |
    | Configure how API responses are formatted.
    |
    */
    'responses' => [
        'include_meta' => true,
        'wrap_response' => true,
        'meta_key' => 'meta',
        'data_key' => 'data',
    ],
];
